### PR TITLE
Add .python-version file for ST4

### PR DESCRIPTION
**Pull request by themilkman**
Hi @ehuss,

first of all thanks for this great plugin!

With this PR ST4 will use the new Python 3.8 plugin-host instead of the old 3.3.
Older ST versions keep using the 3.3, thus this should be 100% backward compatible.

Cheers!

### CODE REVIEW

**Review by ehuss — APPROVED** [review]
Thanks!

**Comment by themilkman** [comment]
Great, thank you! Do you plan to release a new version in the foreseeable future? (-:

**Comment by ehuss** [comment]
Sure!  I'm not sure how long it takes packagecontrol to pick it up, but it should show up eventually.

**Comment by themilkman** [comment]
It arrived, thank you again for your work on this plugin, I am totally used to it in my every-day-work! :pray:

**Pull request merged**
